security:
  basic:
    enabled: false

management:
  security:
    enabled: false

# TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging:
  level:
    root: WARN
    io:
      pivotal: DEBUG
    com:
      netflix: FATAL
#        eureka: INFO #OFF
#        discovery: INFO #OFF
      hystrix.AbstractCommand: DEBUG
    org:
      flywaydb: DEBUG
#        core.internal:
#          dbsupport.SqlScript: DEBUG # SQL only
#          command.DbMigrate: DEBUG

##### spring.cloud.services.registrationMethod #####
# To change value of spring.cloud.services.registrationMethod to 
# "direct" (default is "route"), add "c2c" to active profiles

ribbon: # <---NEW SECTION
  IsSecure: false

#spring:
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}
#
management:
  cloudfoundry:
    skip-ssl-validation: true
